driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64 # 16.04
  - name: ubuntu/trusty64 # 14.04
  - name: centos/7        # 7.3
  - name: centos/6        # 6.8
  - name: debian/jessie64 # 8
  - name: debian/wheezy64 # 7

suites:
  - name: default
    run_list:
    - recipe[cop_tls::dhparams]
    - recipe[cop_tls::snakeoil]
    - recipe[cop_tls::install_certs]
    attributes:
        tls:
            certs:
                test.localhost.org:
                    cert: 'certificate goes here'
                    key: 'private key goes here'
            dhparams:
                bits: 512
                files:
                    - /etc/ssl/certs/dhparams.pem
                    - /tmp/dhparams.pem 
            snakeoil:
                certs:
                    test.localhost.com:
                        bits: 2048
                        days: 400
                        country: US
                        state: Oregon
                        city: Portland
                        company: Copious
                        section: Devoops
                        hostname: test.localhost.com
                        contact: satan@copiousdev.com
